### ISSUE TITLE
Issues for mautic v2.16.5

### ISSUE THREAD

**Issue by MrBoxing** [Leuchtfeuer/mautic-housekeeping-bundle#20]
Can i use this plugin for mautic v2.16.5 ?

After i install plugin and run command php app/console cache:clear, it show this error:

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected 'EventLogCleanup' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/plugins/LeuchtfeuerHousekeepingBundle/Command/EventLogCleanupCommand.php:19
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('MauticPlugin\\Le...')
#2 [internal function]: spl_autoload_call('MauticPlugin\\Le...')
#3 /var/www/html/vendor/symfony/http-kernel/Bundle/Bundle.php(199): ReflectionClass->__construct('MauticPlugin\\Le...')
#4 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(141): Symfony\Component\HttpKernel\Bundle\Bundle->registerCommands(Object(Symfony\Bundle\FrameworkBundle\Console\Application))
#5 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(112): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#6 /v in /var/www/html/plugins/LeuchtfeuerHousekeepingBundle/Command/EventLogCleanupCommand.php on line 19

Can you help me pls ?

Best regards,

Quyen Anh

**Comment by ekkeguembel** [comment]
This plugin currently supports Mautic 4 and Mautic 5, certainly not Mautic 2. I'll put it on the list to update readme and future release notes to our standards which including explicitly naming the versions supported :)

**Comment by MrBoxing** [comment]
> This plugin currently supports Mautic 4 and Mautic 5, certainly not Mautic 2. I'll put it on the list to update readme and future release notes to our standards which including explicitly naming the versions supported :)

Thanks for your answer
